git:
  pagers:
    - colorArg: always
      useExternalDiffGitConfig: true

gui:
  nerdFontsVersion: "3"
  # see also: https://github.com/catppuccin/lazygit/blob/main/themes/macchiato/blue.yml
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8aadf4'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
  authorColors:
    '*': '#b7bdf8'
  language: en
  timeFormat: 2006-01-02
  shortTimeFormat: 13:05:24
  showNumstatInFilesView: true
  border: single